# I leave the creation of the PVC to the reader
# Follow the docs
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apex-deploy
spec:
  selector:
    matchLabels:
      app: apex-ords 
  replicas: 1
  template:
    metadata:
      labels:
        app: apex-ords
    spec:
      initContainers:
      - name: initcopy
        image: #image name #
        command: 
        - sh
        - -c
        - | 
          if [ ! -d "/mnt/myoradata" ] || [ ! "$(ls -A /mnt/moradata)" ]; then
            mv /opt/oracle/oradata /mnt/myoradata
          fi
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: oradatavolume
          mountPath: /mnt
      
      - name: setpermissies
        image: busybox
        command: ["chmod", "-R", "777", "/mnt/myoradata"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: oradatavolume
          mountPath: /mnt

      # De hoofdcontainer
      containers:
        - name: apex-img
          image: # image name #
          ports:
            - containerPort: 1521
              name: port-1521
            - containerPort: 8080
              name: port-8080
          volumeMounts:
            - name: oradatavolume
              mountPath: /opt/oracle/oradata
              subPath: myoradata
      volumes:
        - name: oradatavolume
          persistentVolumeClaim:
            claimName: db-pvc
      imagePullSecrets: 
        - name: ocigeheim
---

apiVersion: v1
kind: Service
metadata:
  name: apex-svc 
spec:
  type: ClusterIP
  ports:
    - name: port-1521
      port: 1521
      protocol: TCP
      targetPort: 1521
    - name: port-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: apex-ords

